file_extension_to_language = {
    '.py': 'Python',
    '.js': 'JavaScript',
    '.ts': 'TypeScript',
    '.jsx': 'JavaScript',
    '.tsx': 'TypeScript',
    '.java': 'Java',
    '.cpp': 'C++',
    '.c': 'C',
    '.h': 'C Header',
    '.hpp': 'C++ Header',
    '.cs': 'C#',
    '.rb': 'Ruby',
    '.go': 'Go',
    '.php': 'PHP',
    '.html': 'HTML',
    '.css': 'CSS',
    '.scss': 'Sass',
    '.less': 'Less',
    '.xml': 'XML',
    '.json': 'JSON',
    '.yml': 'YAML',
    '.yaml': 'YAML',
    '.md': 'Markdown',
    '.sql': 'SQL',
    '.sh': 'Shell',
    '.bash': 'Bash',
    '.zsh': 'Zsh',
    '.pl': 'Perl',
    '.pm': 'Perl Module',
    '.swift': 'Swift',
    '.kt': 'Kotlin',
    '.dart': 'Dart',
    '.rs': 'Rust',
    '.r': 'R',
    '.m': 'Objective-C',
    '.mm': 'Objective-C++',
    '.scala': 'Scala',
    '.erl': 'Erlang',
    '.ex': 'Elixir',
    '.exs': 'Elixir Script',
    '.vb': 'Visual Basic',
    '.f90': 'Fortran',
    '.f95': 'Fortran',
    '.lua': 'Lua',
    '.groovy': 'Groovy',
    '.clj': 'Clojure',
    '.cljs': 'ClojureScript',
    '.coffee': 'CoffeeScript',
    '.nim': 'Nim',
    '.jl': 'Julia',
    '.ps1': 'PowerShell',
    '.bat': 'Batch',
    '.dockerfile': 'Dockerfile',
    '.makefile': 'Makefile',
    '.gradle': 'Gradle',
    '.pom': 'Maven POM',
    '.properties': 'Properties',
    '.ini': 'INI',
    '.toml': 'TOML',
    '.config': 'Configuration File',
    '.tf': 'Terraform',
    '.tfvars': 'Terraform Variables',
    '.rake': 'Rake',
    '.groovy': 'Groovy',
    '.ml': 'OCaml',
    '.pro': 'Prolog',
    '.v': 'Verilog',
    '.sv': 'SystemVerilog',
    '.tex': 'LaTeX',
    '.bib': 'BibTeX',
    '.as': 'ActionScript',
    '.vala': 'Vala',
    '.rkt': 'Racket',
    '.vhd': 'VHDL',
    '.pas': 'Pascal',
    '.d': 'D',
    '.nim': 'Nim',
    '.hs': 'Haskell',
    '.erl': 'Erlang',
    '.hrl': 'Erlang Header',
    ".scss": "sass",
    "Makefile": "Makefile"
}


data_points_to_use = {"code_before",
                      "code_after", "body", "language"}
